# Generated by Django 4.0.5 on 2022-08-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('painting', models.ImageField(blank=True, default=0, null=True, upload_to='paintings')),
                ('long_description', models.TextField()),
                ('price', models.IntegerField()),
                ('short_description', models.TextField(default=0)),
                ('painting_left', models.ImageField(blank=True, default=0, null=True, upload_to='carousel_paintings')),
                ('painting_right', models.ImageField(blank=True, default=0, null=True, upload_to='carousel_paintings')),
                ('painting_top', models.ImageField(blank=True, default=0, null=True, upload_to='carousel_paintings')),
                ('painting_bottom', models.ImageField(blank=True, default=0, null=True, upload_to='carousel_paintings')),
                ('painting_back', models.ImageField(blank=True, default=0, null=True, upload_to='carousel_paintings')),
                ('english_name', models.CharField(default=0, max_length=100)),
                ('english_long_description', models.TextField(blank=True, default=0, null=True)),
                ('english_short_description', models.TextField(blank=True, default=0, null=True)),
                ('dollar_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
