# Generated by Django 4.0.5 on 2022-07-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('painting', models.ImageField(upload_to='paintings')),
                ('long_description', models.TextField()),
                ('price', models.IntegerField()),
                ('short_description', models.TextField()),
                ('painting_left', models.ImageField(upload_to='carousel_paintings')),
                ('painting_right', models.ImageField(upload_to='carousel_paintings')),
                ('painting_top', models.ImageField(upload_to='carousel_paintings')),
                ('painting_bottom', models.ImageField(upload_to='carousel_paintings')),
                ('painting_back', models.ImageField(upload_to='carousel_paintings')),
            ],
        ),
    ]
