# Generated by Django 4.0.5 on 2022-08-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Gallery_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portrait',
            old_name='painting',
            new_name='main_painting',
        ),
        migrations.RenameField(
            model_name='portrait',
            old_name='painting_back',
            new_name='painting_10',
        ),
        migrations.RenameField(
            model_name='portrait',
            old_name='painting_bottom',
            new_name='painting_2',
        ),
        migrations.RenameField(
            model_name='portrait',
            old_name='painting_left',
            new_name='painting_3',
        ),
        migrations.RenameField(
            model_name='portrait',
            old_name='painting_right',
            new_name='painting_4',
        ),
        migrations.RenameField(
            model_name='portrait',
            old_name='painting_top',
            new_name='painting_5',
        ),
        migrations.AddField(
            model_name='portrait',
            name='cm_size',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portrait',
            name='in_size',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portrait',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portrait',
            name='painting_6',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='carousel_paintings'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='painting_7',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='carousel_paintings'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='painting_8',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='carousel_paintings'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='painting_9',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='carousel_paintings'),
        ),
    ]
