# Generated by Django 4.0.5 on 2022-07-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Gallery_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portrait',
            name='painting',
            field=models.ImageField(default=0, upload_to='paintings'),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='painting_back',
            field=models.ImageField(default=0, upload_to='carousel_paintings'),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='painting_bottom',
            field=models.ImageField(default=0, upload_to='carousel_paintings'),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='painting_left',
            field=models.ImageField(default=0, upload_to='carousel_paintings'),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='painting_right',
            field=models.ImageField(default=0, upload_to='carousel_paintings'),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='painting_top',
            field=models.ImageField(default=0, upload_to='carousel_paintings'),
        ),
    ]
