# Generated by Django 4.0.5 on 2022-06-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Gallery_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portraits',
            new_name='Portrait',
        ),
    ]
