# Generated by Django 4.0.5 on 2022-08-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Gallery_App', '0002_rename_painting_portrait_main_painting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='japan_shipping_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portrait',
            name='usa_shipping_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
