# Generated by Django 4.0.5 on 2022-07-01 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Gallery_App', '0002_rename_portraits_portrait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portrait',
            old_name='description',
            new_name='long_description',
        ),
    ]
