# Generated by Django 4.0.5 on 2022-08-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Gallery_App', '0003_alter_portrait_painting_alter_portrait_painting_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='dollar_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='portrait',
            name='english_long_description',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portrait',
            name='english_name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='short_description',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
