# Generated by Django 4.0.5 on 2022-07-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Gallery_App', '0003_rename_description_portrait_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
