# Generated by Django 4.0.5 on 2022-08-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Gallery_App', '0004_portrait_dollar_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='english_short_description',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='short_description',
            field=models.TextField(default=0),
        ),
    ]
