# Generated by Django 4.0.5 on 2022-08-23 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Gallery_App', '0004_alter_portrait_usa_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
