# Generated by Django 4.0.5 on 2022-07-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Gallery_App', '0004_portrait_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='painting_back',
            field=models.ImageField(default=0, upload_to='paintings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portrait',
            name='painting_bottom',
            field=models.ImageField(default=0, upload_to='paintings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portrait',
            name='painting_left',
            field=models.ImageField(default=0, upload_to='paintings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portrait',
            name='painting_right',
            field=models.ImageField(default=0, upload_to='paintings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portrait',
            name='painting_top',
            field=models.ImageField(default=0, upload_to='paintings'),
            preserve_default=False,
        ),
    ]
