# Generated by Django 4.0.5 on 2022-07-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Gallery_App', '0005_portrait_painting_back_portrait_painting_bottom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_front', models.ImageField(upload_to='carousel')),
                ('painting_left', models.ImageField(upload_to='carousel')),
                ('painting_right', models.ImageField(upload_to='carousel')),
                ('painting_top', models.ImageField(upload_to='carousel')),
                ('painting_bottom', models.ImageField(upload_to='carousel')),
                ('painting_back', models.ImageField(upload_to='carousel')),
            ],
        ),
    ]
