# Generated by Django 4.0.5 on 2022-08-23 06:41

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('Art_Gallery_App', '0006_auto_20220823_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portrait',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
