# Generated by Django 4.0.5 on 2022-08-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_account_state_prefecture_account_prefecture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='account',
            name='prefecture',
            field=models.CharField(choices=[('Toyama', '富山県'), ('Kanagawa', '神奈川県'), ('Kochi', '高知県'), ('Iwate', '岩手県'), ('Miyagi', '宮城県'), ('Oita', '大分県'), ('Gunma', '群馬県'), ('Mie', '三重県'), ('Nagano', '長野県'), ('Nagasaki', '長崎県'), ('Tokushima', '徳島県'), ('Shiga', '滋賀県'), ('Miyazaki', '宮崎県'), ('Niigata', '新潟県'), ('Kagoshima', '鹿児島県'), ('Ibaraki', '茨城県'), ('Kumamoto', '熊本県'), ('Yamagata', '山形県'), ('Shizuoka', '静岡県'), ('Akita', '秋田県'), ('Aichi', '愛知県'), ('Fukui', '福井県'), ('Hiroshima', '広島県'), ('Saitama', '埼玉県'), ('Fukushima', '福島県'), ('Yamaguchi', '山口県'), ('Tochigi', '栃木県'), ('Nara', '奈良県'), ('Wakayama', '和歌山県'), ('Kyoto', '京都府'), ('Hyogo', '兵庫県'), ('Yamanashi', '山梨県'), ('Saga', '佐賀県'), ('Osaka', '大阪府'), ('Ishikawa', '石川県'), ('Gifu', '岐阜県'), ('Hokkaido', '北海道'), ('Kagawa', '香川県'), ('Fukuoka', '福岡県'), ('Tottori', '鳥取県'), ('Tokyo', '東京都'), ('Shimane', '島根県'), ('Ehime', '愛媛県'), ('Aomori', '青森県'), ('Chiba', '千葉県'), ('Okayama', '岡山県'), ('Okinawa\t', '沖縄県')], max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('District of Columbia', 'District of Columbia'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virgin Islands', 'Virgin Islands'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming'), ('Armed Forces', 'Armed Forces - AA'), ('Armed Forces Europe', 'Armed Forces Europe - AE'), ('Armed Forces Pacific', 'Armed Forces Pacific - AP'), ('Guam', 'Guam'), ('Puerto Rico', 'Puerto Rico')], max_length=50),
        ),
    ]
