# Generated by Django 4.0.5 on 2022-08-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_phone_number_alter_account_prefecture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, choices=[('JP', 'Japan'), ('US', 'United States')], max_length=2),
        ),
        migrations.AlterField(
            model_name='account',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='prefecture',
            field=models.CharField(blank=True, choices=[('Saitama', '埼玉県'), ('Kanagawa', '神奈川県'), ('Ibaraki', '茨城県'), ('Niigata', '新潟県'), ('Shizuoka', '静岡県'), ('Fukushima', '福島県'), ('Yamanashi', '山梨県'), ('Hyogo', '兵庫県'), ('Shimane', '島根県'), ('Osaka', '大阪府'), ('Okayama', '岡山県'), ('Fukuoka', '福岡県'), ('Kochi', '高知県'), ('Miyagi', '宮城県'), ('Hiroshima', '広島県'), ('Nagano', '長野県'), ('Gunma', '群馬県'), ('Tokushima', '徳島県'), ('Miyazaki', '宮崎県'), ('Chiba', '千葉県'), ('Kagoshima', '鹿児島県'), ('Toyama', '富山県'), ('Aomori', '青森県'), ('Akita', '秋田県'), ('Okinawa\t', '沖縄県'), ('Saga', '佐賀県'), ('Aichi', '愛知県'), ('Ehime', '愛媛県'), ('Tochigi', '栃木県'), ('Kyoto', '京都府'), ('Mie', '三重県'), ('Kagawa', '香川県'), ('Hokkaido', '北海道'), ('Nara', '奈良県'), ('Ishikawa', '石川県'), ('Iwate', '岩手県'), ('Fukui', '福井県'), ('Shiga', '滋賀県'), ('Tokyo', '東京都'), ('Gifu', '岐阜県'), ('Oita', '大分県'), ('Tottori', '鳥取県'), ('Kumamoto', '熊本県'), ('Yamaguchi', '山口県'), ('Wakayama', '和歌山県'), ('Yamagata', '山形県'), ('Nagasaki', '長崎県')], max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(blank=True, choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('District of Columbia', 'District of Columbia'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virgin Islands', 'Virgin Islands'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming'), ('Armed Forces', 'Armed Forces - AA'), ('Armed Forces Europe', 'Armed Forces Europe - AE'), ('Armed Forces Pacific', 'Armed Forces Pacific - AP'), ('Guam', 'Guam'), ('Puerto Rico', 'Puerto Rico')], max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='street1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
