# Generated by Django 4.0.5 on 2022-08-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_account_country_alter_account_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='account',
            name='prefecture',
            field=models.CharField(blank=True, choices=[('Hyogo', '兵庫県'), ('Shizuoka', '静岡県'), ('Gifu', '岐阜県'), ('Mie', '三重県'), ('Wakayama', '和歌山県'), ('Kanagawa', '神奈川県'), ('Tokushima', '徳島県'), ('Okayama', '岡山県'), ('Aichi', '愛知県'), ('Miyagi', '宮城県'), ('Osaka', '大阪府'), ('Kagoshima', '鹿児島県'), ('Yamanashi', '山梨県'), ('Saga', '佐賀県'), ('Yamagata', '山形県'), ('Tochigi', '栃木県'), ('Yamaguchi', '山口県'), ('Nara', '奈良県'), ('Tottori', '鳥取県'), ('Shiga', '滋賀県'), ('Shimane', '島根県'), ('Aomori', '青森県'), ('Ibaraki', '茨城県'), ('Hokkaido', '北海道'), ('Fukui', '福井県'), ('Toyama', '富山県'), ('Tokyo', '東京都'), ('Nagano', '長野県'), ('Nagasaki', '長崎県'), ('Fukushima', '福島県'), ('Hiroshima', '広島県'), ('Okinawa\t', '沖縄県'), ('Iwate', '岩手県'), ('Kyoto', '京都府'), ('Niigata', '新潟県'), ('Kagawa', '香川県'), ('Kochi', '高知県'), ('Fukuoka', '福岡県'), ('Ehime', '愛媛県'), ('Akita', '秋田県'), ('Gunma', '群馬県'), ('Ishikawa', '石川県'), ('Kumamoto', '熊本県'), ('Miyazaki', '宮崎県'), ('Oita', '大分県'), ('Saitama', '埼玉県'), ('Chiba', '千葉県')], max_length=50),
        ),
    ]
