# Generated by Django 4.0.5 on 2022-08-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_account_prefecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='prefecture',
            field=models.CharField(blank=True, choices=[('Aomori', '青森県'), ('Miyazaki', '宮崎県'), ('Fukui', '福井県'), ('Hiroshima', '広島県'), ('Fukuoka', '福岡県'), ('Aichi', '愛知県'), ('Tokyo', '東京都'), ('Ishikawa', '石川県'), ('Kumamoto', '熊本県'), ('Yamanashi', '山梨県'), ('Yamaguchi', '山口県'), ('Hyogo', '兵庫県'), ('Oita', '大分県'), ('Gunma', '群馬県'), ('Niigata', '新潟県'), ('Gifu', '岐阜県'), ('Toyama', '富山県'), ('Hokkaido', '北海道'), ('Nara', '奈良県'), ('Ibaraki', '茨城県'), ('Kanagawa', '神奈川県'), ('Yamagata', '山形県'), ('Ehime', '愛媛県'), ('Iwate', '岩手県'), ('Saitama', '埼玉県'), ('Wakayama', '和歌山県'), ('Shimane', '島根県'), ('Kochi', '高知県'), ('Nagano', '長野県'), ('Tochigi', '栃木県'), ('Saga', '佐賀県'), ('Okinawa\t', '沖縄県'), ('Akita', '秋田県'), ('Mie', '三重県'), ('Tokushima', '徳島県'), ('Miyagi', '宮城県'), ('Shizuoka', '静岡県'), ('Nagasaki', '長崎県'), ('Okayama', '岡山県'), ('Tottori', '鳥取県'), ('Kagoshima', '鹿児島県'), ('Fukushima', '福島県'), ('Kagawa', '香川県'), ('Chiba', '千葉県'), ('Kyoto', '京都府'), ('Shiga', '滋賀県'), ('Osaka', '大阪府')], max_length=50),
        ),
    ]
