# Generated by Django 4.0.5 on 2022-08-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_account_prefecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, choices=[('JP', '日本'), ('US', 'United States')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='prefecture',
            field=models.CharField(blank=True, choices=[('Tochigi', '栃木県'), ('Tokyo', '東京都'), ('Aichi', '愛知県'), ('Niigata', '新潟県'), ('Fukuoka', '福岡県'), ('Yamagata', '山形県'), ('Tottori', '鳥取県'), ('Miyazaki', '宮崎県'), ('Hiroshima', '広島県'), ('Akita', '秋田県'), ('Saitama', '埼玉県'), ('Kagawa', '香川県'), ('Kagoshima', '鹿児島県'), ('Okayama', '岡山県'), ('Gunma', '群馬県'), ('Aomori', '青森県'), ('Shizuoka', '静岡県'), ('Saga', '佐賀県'), ('Okinawa\t', '沖縄県'), ('Oita', '大分県'), ('Wakayama', '和歌山県'), ('Nagasaki', '長崎県'), ('Miyagi', '宮城県'), ('Ehime', '愛媛県'), ('Kochi', '高知県'), ('Kyoto', '京都府'), ('Shimane', '島根県'), ('Nagano', '長野県'), ('Kumamoto', '熊本県'), ('Fukushima', '福島県'), ('Hyogo', '兵庫県'), ('Ibaraki', '茨城県'), ('Tokushima', '徳島県'), ('Toyama', '富山県'), ('Nara', '奈良県'), ('Shiga', '滋賀県'), ('Ishikawa', '石川県'), ('Yamaguchi', '山口県'), ('Mie', '三重県'), ('Gifu', '岐阜県'), ('Kanagawa', '神奈川県'), ('Hokkaido', '北海道'), ('Yamanashi', '山梨県'), ('Fukui', '福井県'), ('Chiba', '千葉県'), ('Osaka', '大阪府'), ('Iwate', '岩手県')], max_length=50, null=True),
        ),
    ]
