# Generated by Django 4.0.5 on 2022-08-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_account_country_alter_account_prefecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='prefecture',
            field=models.CharField(blank=True, choices=[('Shimane', '島根県'), ('Hyogo', '兵庫県'), ('Tochigi', '栃木県'), ('Fukui', '福井県'), ('Hokkaido', '北海道'), ('Chiba', '千葉県'), ('Saga', '佐賀県'), ('Akita', '秋田県'), ('Yamaguchi', '山口県'), ('Osaka', '大阪府'), ('Wakayama', '和歌山県'), ('Iwate', '岩手県'), ('Niigata', '新潟県'), ('Tokyo', '東京都'), ('Ehime', '愛媛県'), ('Miyazaki', '宮崎県'), ('Aichi', '愛知県'), ('Kochi', '高知県'), ('Saitama', '埼玉県'), ('Kagoshima', '鹿児島県'), ('Nara', '奈良県'), ('Mie', '三重県'), ('Miyagi', '宮城県'), ('Kanagawa', '神奈川県'), ('Fukushima', '福島県'), ('Kagawa', '香川県'), ('Fukuoka', '福岡県'), ('Ishikawa', '石川県'), ('Yamagata', '山形県'), ('Oita', '大分県'), ('Shiga', '滋賀県'), ('Kyoto', '京都府'), ('Nagano', '長野県'), ('Tottori', '鳥取県'), ('Ibaraki', '茨城県'), ('Nagasaki', '長崎県'), ('Aomori', '青森県'), ('Okayama', '岡山県'), ('Kumamoto', '熊本県'), ('Hiroshima', '広島県'), ('Toyama', '富山県'), ('Tokushima', '徳島県'), ('Okinawa\t', '沖縄県'), ('Gifu', '岐阜県'), ('Gunma', '群馬県'), ('Shizuoka', '静岡県'), ('Yamanashi', '山梨県')], max_length=50, null=True),
        ),
    ]
