# Generated by Django 4.0.5 on 2022-08-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_account_prefecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='prefecture',
            field=models.CharField(blank=True, choices=[('Miyagi', '宮城県'), ('Hyogo', '兵庫県'), ('Yamaguchi', '山口県'), ('Hokkaido', '北海道'), ('Aichi', '愛知県'), ('Ehime', '愛媛県'), ('Kagawa', '香川県'), ('Oita', '大分県'), ('Nagano', '長野県'), ('Niigata', '新潟県'), ('Wakayama', '和歌山県'), ('Kagoshima', '鹿児島県'), ('Gunma', '群馬県'), ('Fukushima', '福島県'), ('Nara', '奈良県'), ('Gifu', '岐阜県'), ('Nagasaki', '長崎県'), ('Tokushima', '徳島県'), ('Chiba', '千葉県'), ('Kochi', '高知県'), ('Okinawa\t', '沖縄県'), ('Miyazaki', '宮崎県'), ('Yamanashi', '山梨県'), ('Osaka', '大阪府'), ('Yamagata', '山形県'), ('Saga', '佐賀県'), ('Aomori', '青森県'), ('Fukui', '福井県'), ('Tottori', '鳥取県'), ('Iwate', '岩手県'), ('Shiga', '滋賀県'), ('Kanagawa', '神奈川県'), ('Toyama', '富山県'), ('Mie', '三重県'), ('Akita', '秋田県'), ('Shimane', '島根県'), ('Saitama', '埼玉県'), ('Ishikawa', '石川県'), ('Hiroshima', '広島県'), ('Tokyo', '東京都'), ('Tochigi', '栃木県'), ('Kumamoto', '熊本県'), ('Ibaraki', '茨城県'), ('Fukuoka', '福岡県'), ('Okayama', '岡山県'), ('Kyoto', '京都府'), ('Shizuoka', '静岡県')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(blank=True, choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('District of Columbia', 'District of Columbia'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virgin Islands', 'Virgin Islands'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming'), ('Armed Forces', 'Armed Forces - AA'), ('Armed Forces Europe', 'Armed Forces Europe - AE'), ('Armed Forces Pacific', 'Armed Forces Pacific - AP'), ('Guam', 'Guam'), ('Puerto Rico', 'Puerto Rico')], max_length=50, null=True),
        ),
    ]
